import { roles } from "../../config.json";

export const [
  TwoCharacters,
  TwoCharactersWithSymbol,
  ThreeCharacters,
  ThreeCharactersWithSymbol,
  FourCharacters,
  FourCharactersWithSymbol,
  Repeated,
  Word,
  Users,
  Partner,
  DiscordModerator,
  BugHunterLevel2,
  BugHunterLevel1,
  Hypesquad,
  Developer,
  EarlySupporter,
] = [
  roles["2c"],
  roles["2cs"],
  roles["3c"],
  roles["3cs"],
  roles["4c"],
  roles["4cs"],
  roles["repeated"],
  roles["word"],
  roles["users"],
  roles["partner"],
  roles["mod"],
  roles["bugHunter2"],
  roles["bugHunter1"],
  roles["hypesquad"],
  roles["developer"],
  roles["early"],
];
